spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drawing_match
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  threads:
    virtual:
      enabled: true
#  kafka:
#    bootstrap-servers: localhost:19092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#  rabbitmq:
#    host: "${custom.rabbitmq.host}"
#    port: "${custom.rabbitmq.port}"
#    stompPort: "${custom.rabbitmq.stompPort}"
#    username: "${custom.rabbitmq.username}"
#    password: "${custom.rabbitmq.password}"

logging:
  level:
    com.example.matchingdrawing : debug
    org.hibernate.sql : debug
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
#    org.springframework.kafka : debug

custom:
  site:
    product:
      domain: localhost
      frontUrl: "https://${custom.site.product.domain}:${server.port}"
      backUrl: "https://${custom.site.product.domain}:${server.port}"
#  jwt:
#    secretKey: ${custom.jwt.key}